name: update
on: 
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute sh script 
        run: |
         shopt -s globstar
         git clone https://github.com/ProgramComputer/hostsblock.git
         cd **/hostsblock
         make
         cd -
         git clone https://github.com/easylist/easylist.git
         subdirectories=("./easylist/easylist" "./easylist/easylist_adult" "./easylist/easylist_cookie" "./easylist/easyprivacy" "./easylist/fanboy-addon")
         
         for dir in "${subdirectories[@]}"; do
             for file in "$dir"/*; do
                if [ -f "$file" ]; then
            echo "Processing file: $file"
           mkdir -p $file;
           echo $file;
           ./$file | ./hostsblock/hostsblock - > ./EasyListMirror/$dir/$file/hosts;
                fi
          done
         done
         sudo rm -rf hostsblock
         sudo rm -rf easylist
        env:
          key: ${{ secrets.key }} # if run.py requires passwords..etc, set it as secrets
      - name: Commit files # transfer the new html files back into the repository
        run: |
         git config --local user.name "Update"
         git add .
         git commit -m "Updating the hosts file"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         force: true
